### PR TITLE
migrating to CryptSharpOfficial-2.0.0

### PR DESCRIPTION
**Pull request by tuler**
CryptSharp is now maintained by the package CryptSharpOfficial

### CODE REVIEW

**Comment by caevyn** [comment]
Messed up merging this one, Package is now updated. Thanks for your PRs:)

**Comment by tuler** [comment]
Thanks for your code. Do you have plans to publish do nuget?

**Comment by caevyn** [comment]
I can do, I didn't think anyone was using it except me:)

**Comment by tuler** [comment]
I plan to use it.I see you use a dot to separate parts of the  hashed password. I'm not a security expert, but is this recommended?

Thanks,

Danilo
—

**Comment by caevyn** [comment]
*PBKDF2 (I'm always getting the letters in the wrong order :)

**Comment by tuler** [comment]
Thanks! I was wondering if the dot gives an unnecessary hint for an attacker about the size of the salt. But as I said, I'm not an expert.

I'd stick with standard HMACSHA1, but security experts in the company are being picky about it :-p

**Comment by caevyn** [comment]
Sounds familiar. Had a few false starts with the package.
https://www.nuget.org/packages/Malt.PasswordHasher/1.0.2
Let me know if there are any problems.
Looks like Brock Allen does similar concatenation in his if that is of any
comfort:)
Also worth noting that the iterations recommended by OWASP are for HMACSHA1
so if your security guys want HMACSHA512 and the OWASP recommended
iterations you could end up with performance issues. I recommend tuning the
iterations to your hardware.
Matt.

**Comment by tuler** [comment]
I'll stick with 5000 iterations.
1.0.2 is in place already.
Thanks!

**Pull request closed without merging**
